# Generated by Django 4.0.6 on 2022-07-06 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Translations',
            fields=[
                ('TranslationId', models.AutoField(primary_key=True, serialize=False)),
                ('TranslationInputs', models.CharField(max_length=500)),
                ('TranslationOutputs', models.CharField(max_length=500)),
            ],
        ),
    ]
